# Generated by Django 4.1.7 on 2023-04-02 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('mob', models.PositiveIntegerField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dest', models.TextField()),
                ('name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('attendees', models.ManyToManyField(related_name='trips_attended', to='todo.user')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_created', to='todo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_user', to='todo.user')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_trip', to='todo.trip')),
            ],
        ),
    ]
